### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by iis4u2nv**

### CODE REVIEW

**Comment by iis4u2nv** [comment]
I revised the file just now for your review and approval.
Note: the new screen shot will be taken tomorrow and pushed again for your review and approval.

**Review by marbfree — APPROVED** [review]
Awesome!  Thanks Amazing.

**Comment by iis4u2nv** [comment]
I revised the picture and added links. Please review and approve. Thank you.

**Review by iis4u2nv — COMMENTED** [review]
Please review and approve.

**Review by marbfree — APPROVED** [review]

**Review by dtm589 — APPROVED** [review]

**Comment by iis4u2nv** [comment]
Added more text.

**Pull request merged**
